# .streamlit/config.toml
[server]
headless = true
enableCORS = true
port = $PORT
enableXsrfProtection = true

[theme]
primaryColor="#d33682"
backgroundColor="#002b36"
secondaryBackgroundColor="#586e75"
textColor="#fafafa"
font="sans serif"
